language: java
jdk:
  - oraclejdk8

env:
  - SERVER=payara-ci-managed-update,payara-ci-managed,provided
  - SERVER=wildfly,weld-decorator-bundled,bundled
  - SERVER=tomee,bundled
  - SERVER=openliberty,bundled
script: mvn clean install -P $SERVER

